### PR TITLE
Switching own posts functionality

### PR DESCRIPTION
**Pull request by gwennie-chan**
Changing the thingifier link into an injected button link on the forum overview pages.

### CODE REVIEW

**Comment by Alice-Cheshire** [comment]
After finally getting a chance to test this, there seems to be a major issue. When it sets your user ID stuff there seems to be no own posts link at all.

**Comment by gwennie-chan** [comment]
I get the button but the link is related to being able to store data. The script is flat out not storing any data options for some reason. You're free to try to see if you can fix it because you designed the persistent storage system.

**Comment by Alice-Cheshire** [comment]
Are you referring to the settings issue you opened for that latter part? If so then I'm not sure what your issue is. I've tested the script on both Firefox and Chrome and it worked fine for me on both. You might try resetting the script's settings.

**Comment by gwennie-chan** [comment]
I have and it never saves anything :(

**Comment by Alice-Cheshire** [comment]
What browser and version of the browser are you using? And are there any errors in the console? Also you might check to make certain you're using the current release version. With personal versions as well as testing dev code in the past I know I've forgotten to revert back to the release version in the past myself and it took me way longer than it should've to figure it out.

**Comment by gwennie-chan** [comment]
Ah that's it switching code back. I'm using Firefox 57 release version currently. Regardless, this branch would be great but I can't figure out why it's not storing or saving data.

**Comment by Alice-Cheshire** [comment]
Up to date Firefox release channel is my primary browser too. I'm not really sure why it's not handling data properly on your version. As far as I can see you're not changing anything related to saving or loading data. I do see two issues though now that I look closer. The first is fairly minor and that's just an if-else block. You're doing if then else if when it's not really necessary here to bother with the second check. That one's a minor issue however. The other one is a $ on line 464. Your code is this:
```javascript
$('.btn-group:nth-of-type(2)').after('<div class="btn-group"><a class="btn" href="forums/posts?user_id=$' + DT.yourid + '">Your Posts</a></div>');
```
It'd work better as this:
```javascript
$('.btn-group:nth-of-type(2)').after(`<div class="btn-group"><a class="btn" href="forums/posts?user_id=${DT.yourid}">Your Posts</a></div>`);
```
If you use backticks to declare a string in Javascript then you can just call variables directly in the string itself using ${var}.

I don't think this bug would result in the issues this version has though still.

**Comment by Alice-Cheshire** [comment]
Have you fixed the issue with the link not appearing after it sets your user id too? On the last version I'd checked and it does indeed look to be setting your user id so it seems to be an issue with the code you changed for creating the link.

**Pull request closed without merging**
